# Generated by Django 5.0.6 on 2026-05-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='readme',
            field=models.TextField(blank=True, default=''),
        ),
    ]
